### PR TITLE
[FEATURE] Add flush preview image button

### PR DESCRIPTION
**Pull request by nhovratov**
It is now possible to selectively delete Youtube preview images from within the backend. A new button is added next to the inline record control buttons (right next to the drag move button). A notification will appear upon clicking, which will notify the user of the success of the operation.

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @nhovratov 

Thank you for your pull request. Unfortunately this one only handles images for/from YouTube videos. I would love to see some solution for all available handlers. Maybe introduce some further functions in the interface that can decide if a deletion needs to be handled and can handle the deletion within their specific image services.

**Comment by nhovratov** [comment]
Hi @IchHabRecht ,
thanks for your feedback. I generalized the approach, so it works now for both youtube and vimeo. Other services do not come from FAL and cannot be flushed in the IRRE view. I hope this is fine.

**Comment by franzkugelmann** [comment]
Just tested this feature with youtube previews. Works exactly as expected! Thanks @nhovratov

**Comment by IchHabRecht** [comment]
Hi @nhovratov @franzkugelmann 

I updated this pull request and added a proper event listener for TYPO3 12.4 - would you mind to test the feature again.

**Comment by franzkugelmann** [comment]
Thanks @IchHabRecht ! Just ran some manual tests. This flush preview image button pull request works for both youtube and vimeo with dev-main in TYPO3 11 and TYPO3 12.

**Pull request merged**
