### PR TITLE
[TASK] Raise compatibility to TYPO3 12.4

### PR DESCRIPTION
**Pull request by IchHabRecht**

### CODE REVIEW

**Comment by mbrodala** [comment]
Are there plans to refresh this for the TYPO3v12 stable version and thus add support for this TYPO3 version?

**Comment by mbrodala** [comment]
@franzkugelmann @SvenJuergens Maybe you can add some details if and how development can proceed here?

**Comment by SvenJuergens** [comment]
hi, @mbrodala 
I would also be happy if the  extension became v12 compatible. However, as it is a project solely by @IchHabRecht , only she can take further steps.

**Comment by IchHabRecht** [comment]
I changed the compatibility of the current pull request. Maybe anyone can check the branch https://github.com/IchHabRecht/social_gdpr/tree/compatibility-12-1 (just ignore the name ;-) )

**Comment by franzkugelmann** [comment]
Tested this branch with v11 and v12, with and without modified fluid templates. Looks good to me!

**Comment by mbrodala** [comment]
Tested on a TYPO3v11 and it still works fine. Test on TYPO3v12 is pending.

**Comment by mbrodala** [comment]
Works fine here on TYPO3v12 BTW. ;-)

**Pull request merged**
